name: Manually generate documentation

on:
  workflow_dispatch

jobs:
  generate-documentation:
    name: Generate documentation for release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate documentation and upload
        uses: docker://ponylang/library-documentation-action:0.1.6
        with:
          site_url: "https://redvers.github.io/pony-libzip/"
          library_name: "ponyzip"
          docs_build_dir: "build/ponyzip-docs"
          git_user_name: "redvers"
          git_user_email: "red@infect.me"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
